name: 7/24 Canli Veri Toplayici

on:
  schedule:
    # Her 5 dakikada bir otomatik tetiklenir
    - cron: '3,18,33,48 * * * *'
  workflow_dispatch: # İstediğimizde elle de başlatabilmek için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodlari Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-state: '3.10'

    - name: Kutuphaneleri Yukle
      run: |
        pip install pandas selenium webdriver-manager

    - name: Botu Çalistir (Veri Cek)
      run: python veri_cekici.py

    - name: Isik Hizinda Grup Analiz Raporu Uret
      run: python grup_analizi.py

    - name: Yeni Verileri GitHub'a Geri Kaydet
      run: |
        git config --global user.name 'Veri Botu'
        git config --global user.email 'bot@github.com'
        git add hizli_on_numara.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "✨ Bot: Yeni çekiliş verileri eklendi" && git push)
